CREATE TABLE abt AS 

WITH results AS (
    SELECT 
        uuid,
        result,
        time_class,
        CASE 
            WHEN result = '1-0' THEN 'white' 
            WHEN result = '0-1' THEN 'black' 
            ELSE 'draw'
        END AS result_desc

    FROM matches
),

upset_tb AS (

    SELECT 
        t2.result_desc,
        t2.uuid,
        t2.time_class,
        t1.elo_diff,
        t1.turn,
        CASE 
            WHEN result_desc = 'white' AND elo_diff >= 0 THEN 0
            WHEN result_desc = 'black' AND elo_diff <= 0 THEN 0
            WHEN result_desc = 'draw' THEN 0
            ELSE 1
        END AS fl_upset
    FROM feature_store AS t1 

    LEFT JOIN results AS t2
    ON t1.uuid = t2.uuid

    GROUP BY t1.uuid
)

SELECT

    t1.uuid,
    t1.ply_count,
    t2.fl_upset,
    t1.time_control,
    t2.time_class,
    t1.turn,
    t1.elo_diff,
    t1.time_diff,
    t1.move_piece,
    t1.is_capture,
    t1.is_irreversible,
    t1.gives_check,
    t1.is_2_repetition,
    t1.has_2_repetition,
    t1.has_promotion,
    t1.is_trade,
    t1.has_castled,
    t1.has_king_castled,
    t1.has_queen_castled,
    t1.opp_has_2_repetition,
    t1.opp_has_promotion,
    t1.opp_has_castled,
    t1.opp_has_queen_castled,
    t1.opp_has_king_castled,
    t1.qtde_pawn,
    t1.qtde_knight,
    t1.qtde_bishop,
    t1.qtde_rook,
    t1.qtde_queen,
    t1.qtde_king,
    t1.diff_pawn,
    t1.diff_knight,
    t1.diff_bishop,
    t1.diff_rook,
    t1.diff_queen,
    t1.diff_king,
    t1.qtde_gives_check,
    t1.qtde_capture,
    t1.qtde_irreversible,
    t1.recency_capture,
    t1.recency_gives_check,
    t1.recency_is_irreversible,
    t1.recency_pawn_move,
    t1.recency_knight_move,
    t1.recency_bishop_move,
    t1.recency_rook_move,
    t1.recency_queen_move,
    t1.recency_king_move,
    t1.opp_qtde_capture,
    t1.opp_qtde_irreversible,
    t1.opp_recency_pawn_piece,
    t1.opp_recency_knight_piece,
    t1.opp_recency_bishop_piece,
    t1.opp_recency_rook_piece,
    t1.opp_recency_queen_piece,
    t1.opp_recency_king_piece,
    t1.opp_recency_capture,
    t1.opp_recency_gives_check,
    t1.opp_recency_is_irreversible,
    t1.time_diff_d1,
    t1.time_diff_d3,
    t1.time_diff_d5,
    t1.move_piece_d1,
    t1.move_piece_d3,
    t1.move_piece_d5,
    t1.is_capture_d1,
    t1.is_capture_d3,
    t1.is_capture_d5,
    t1.is_irreversible_d1,
    t1.is_irreversible_d3,
    t1.is_irreversible_d5,
    t1.gives_check_d1,
    t1.gives_check_d3,
    t1.gives_check_d5,
    t1.is_2_repetition_d1,
    t1.is_2_repetition_d3,
    t1.is_2_repetition_d5,
    t1.has_2_repetition_d1,
    t1.has_2_repetition_d3,
    t1.has_2_repetition_d5,
    t1.has_promotion_d1,
    t1.has_promotion_d3,
    t1.has_promotion_d5,
    t1.is_trade_d1,
    t1.is_trade_d3,
    t1.is_trade_d5,
    t1.has_castled_d1,
    t1.has_castled_d3,
    t1.has_castled_d5,
    t1.has_king_castled_d1,
    t1.has_king_castled_d3,
    t1.has_king_castled_d5,
    t1.has_queen_castled_d1,
    t1.has_queen_castled_d3,
    t1.has_queen_castled_d5,
    t1.opp_has_2_repetition_d1,
    t1.opp_has_2_repetition_d3,
    t1.opp_has_2_repetition_d5,
    t1.opp_has_promotion_d1,
    t1.opp_has_promotion_d3,
    t1.opp_has_promotion_d5,
    t1.opp_has_castled_d1,
    t1.opp_has_castled_d3,
    t1.opp_has_castled_d5,
    t1.opp_has_queen_castled_d1,
    t1.opp_has_queen_castled_d3,
    t1.opp_has_queen_castled_d5,
    t1.opp_has_king_castled_d1,
    t1.opp_has_king_castled_d3,
    t1.opp_has_king_castled_d5,
    t1.qtde_pawn_d1,
    t1.qtde_pawn_d3,
    t1.qtde_pawn_d5,
    t1.qtde_knight_d1,
    t1.qtde_knight_d3,
    t1.qtde_knight_d5,
    t1.qtde_bishop_d1,
    t1.qtde_bishop_d3,
    t1.qtde_bishop_d5,
    t1.qtde_rook_d1,
    t1.qtde_rook_d3,
    t1.qtde_rook_d5,
    t1.qtde_queen_d1,
    t1.qtde_queen_d3,
    t1.qtde_queen_d5,
    t1.qtde_king_d1,
    t1.qtde_king_d3,
    t1.qtde_king_d5,
    t1.diff_pawn_d1,
    t1.diff_pawn_d3,
    t1.diff_pawn_d5,
    t1.diff_knight_d1,
    t1.diff_knight_d3,
    t1.diff_knight_d5,
    t1.diff_bishop_d1,
    t1.diff_bishop_d3,
    t1.diff_bishop_d5,
    t1.diff_rook_d1,
    t1.diff_rook_d3,
    t1.diff_rook_d5,
    t1.diff_queen_d1,
    t1.diff_queen_d3,
    t1.diff_queen_d5,
    t1.diff_king_d1,
    t1.diff_king_d3,
    t1.diff_king_d5,
    t1.qtde_gives_check_d1,
    t1.qtde_gives_check_d3,
    t1.qtde_gives_check_d5,
    t1.qtde_capture_d1,
    t1.qtde_capture_d3,
    t1.qtde_capture_d5,
    t1.qtde_irreversible_d1,
    t1.qtde_irreversible_d3,
    t1.qtde_irreversible_d5,
    t1.recency_capture_d1,
    t1.recency_capture_d3,
    t1.recency_capture_d5,
    t1.recency_gives_check_d1,
    t1.recency_gives_check_d3,
    t1.recency_gives_check_d5,
    t1.recency_is_irreversible_d1,
    t1.recency_is_irreversible_d3,
    t1.recency_is_irreversible_d5,
    t1.recency_pawn_move_d1,
    t1.recency_pawn_move_d3,
    t1.recency_pawn_move_d5,
    t1.recency_knight_move_d1,
    t1.recency_knight_move_d3,
    t1.recency_knight_move_d5,
    t1.recency_bishop_move_d1,
    t1.recency_bishop_move_d3,
    t1.recency_bishop_move_d5,
    t1.recency_rook_move_d1,
    t1.recency_rook_move_d3,
    t1.recency_rook_move_d5,
    t1.recency_queen_move_d1,
    t1.recency_queen_move_d3,
    t1.recency_queen_move_d5,
    t1.recency_king_move_d1,
    t1.recency_king_move_d3,
    t1.recency_king_move_d5,
    t1.opp_qtde_capture_d1,
    t1.opp_qtde_capture_d3,
    t1.opp_qtde_capture_d5,
    t1.opp_qtde_irreversible_d1,
    t1.opp_qtde_irreversible_d3,
    t1.opp_qtde_irreversible_d5,
    t1.opp_recency_pawn_piece_d1,
    t1.opp_recency_pawn_piece_d3,
    t1.opp_recency_pawn_piece_d5,
    t1.opp_recency_knight_piece_d1,
    t1.opp_recency_knight_piece_d3,
    t1.opp_recency_knight_piece_d5,
    t1.opp_recency_bishop_piece_d1,
    t1.opp_recency_bishop_piece_d3,
    t1.opp_recency_bishop_piece_d5,
    t1.opp_recency_rook_piece_d1,
    t1.opp_recency_rook_piece_d3,
    t1.opp_recency_rook_piece_d5,
    t1.opp_recency_queen_piece_d1,
    t1.opp_recency_queen_piece_d3,
    t1.opp_recency_queen_piece_d5,
    t1.opp_recency_king_piece_d1,
    t1.opp_recency_king_piece_d3,
    t1.opp_recency_king_piece_d5,
    t1.opp_recency_capture_d1,
    t1.opp_recency_capture_d3,
    t1.opp_recency_capture_d5,
    t1.opp_recency_gives_check_d1,
    t1.opp_recency_gives_check_d3,
    t1.opp_recency_gives_check_d5,
    t1.opp_recency_is_irreversible_d1,
    t1.opp_recency_is_irreversible_d3,
    t1.opp_recency_is_irreversible_d5

FROM feature_store AS t1

LEFT JOIN upset_tb AS t2 
ON t1.uuid = t2.uuid
