CREATE TABLE IF NOT EXISTS matches (
    uuid TEXT PRIMARY KEY,
    url TEXT,
    date TEXT,
    eco TEXT,
    time_control TEXT,
    white_acc REAL,
    white_result TEXT,
    white_elo TEXT,
    white_username TEXT,
    white_uuid TEXT,
    black_acc REAL,
    black_result TEXT,
    black_elo TEXT,
    black_username TEXT,
    black_uuid TEXT,
    end_time INTEGER,
    rated INTEGER,
    tcn TEXT,
    initial_setup TEXT,
    fen TEXT,
    time_class TEXT,
    rules TEXT,
    tournament TEXT,
    event TEXT,
    round TEXT,
    result TEXT,
    current_position TEXT,
    ecu_url TEXT,
    termination TEXT,
    start_time TEXT,
    moves TEXT
);